# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4425e661bc3d5447acc80d828739db2330d160f764165553980b56007485a93b72660257f7abfcb324c6ac90670441e9da4bf7ddcf69887647732e6004bc911d

test:
  secret_key_base: 398702f7c30f98a0ddc31ef8e391883255564739349a6fc2906163902417a6ceb415ab8d870558872f476606181cc9abb2a04027eff2155c10769fe96cf969e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
